<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="2" ignored="0" total="7" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Dependency Test Suite" duration-ms="39" started-at="2017-03-30T19:13:18Z" finished-at="2017-03-30T19:13:18Z">
    <groups>
      <group name="testng.second">
        <method signature="DependsOnTesting.Method5()[pri:0, instance:testPackage.DependsOnTesting@6d8a00e3]" name="Method5" class="testPackage.DependsOnTesting"/>
      </group> <!-- testng.second -->
      <group name="testng.first">
        <method signature="DependsOnTesting.Method4()[pri:0, instance:testPackage.DependsOnTesting@6d8a00e3]" name="Method4" class="testPackage.DependsOnTesting"/>
      </group> <!-- testng.first -->
      <group name="testng.third">
        <method signature="DependsOnTesting.Method6()[pri:0, instance:testPackage.DependsOnTesting@6d8a00e3]" name="Method6" class="testPackage.DependsOnTesting"/>
      </group> <!-- testng.third -->
    </groups>
    <test name="DependencyTest" duration-ms="39" started-at="2017-03-30T19:13:18Z" finished-at="2017-03-30T19:13:18Z">
      <class name="testPackage.DependsOnTesting">
        <test-method status="PASS" signature="Method1()[pri:0, instance:testPackage.DependsOnTesting@6d8a00e3]" name="Method1" duration-ms="9" started-at="2017-03-30T22:13:18Z" finished-at="2017-03-30T22:13:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Method1 -->
        <test-method status="FAIL" signature="Method2()[pri:0, instance:testPackage.DependsOnTesting@6d8a00e3]" name="Method2" duration-ms="2" started-at="2017-03-30T22:13:18Z" finished-at="2017-03-30T22:13:18Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at testPackage.DependsOnTesting.Method2(DependsOnTesting.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Method2 -->
        <test-method status="PASS" signature="Method4()[pri:0, instance:testPackage.DependsOnTesting@6d8a00e3]" name="Method4" duration-ms="1" started-at="2017-03-30T22:13:18Z" finished-at="2017-03-30T22:13:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Method4 -->
        <test-method status="FAIL" signature="Method5()[pri:0, instance:testPackage.DependsOnTesting@6d8a00e3]" name="Method5" duration-ms="1" started-at="2017-03-30T22:13:18Z" finished-at="2017-03-30T22:13:18Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at testPackage.DependsOnTesting.Method5(DependsOnTesting.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Method5 -->
        <test-method status="PASS" signature="Method6()[pri:0, instance:testPackage.DependsOnTesting@6d8a00e3]" name="Method6" duration-ms="1" started-at="2017-03-30T22:13:18Z" finished-at="2017-03-30T22:13:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Method6 -->
        <test-method status="SKIP" signature="Method3()[pri:0, instance:testPackage.DependsOnTesting@6d8a00e3]" name="Method3" duration-ms="0" started-at="2017-03-30T22:13:18Z" depends-on-methods="testPackage.DependsOnTesting.Method2" finished-at="2017-03-30T22:13:18Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DependsOnTesting.Method3()[pri:0, instance:testPackage.DependsOnTesting@6d8a00e3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DependsOnTesting.Method3()[pri:0, instance:testPackage.DependsOnTesting@6d8a00e3] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Method3 -->
        <test-method status="SKIP" signature="Method7()[pri:0, instance:testPackage.DependsOnTesting@6d8a00e3]" name="Method7" duration-ms="0" depends-on-groups="testng.*" started-at="2017-03-30T22:13:18Z" finished-at="2017-03-30T22:13:18Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DependsOnTesting.Method7()[pri:0, instance:testPackage.DependsOnTesting@6d8a00e3] depends on not successfully finished methods in group "testng.*"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DependsOnTesting.Method7()[pri:0, instance:testPackage.DependsOnTesting@6d8a00e3] depends on not successfully finished methods in group "testng.*"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Method7 -->
      </class> <!-- testPackage.DependsOnTesting -->
    </test> <!-- DependencyTest -->
  </suite> <!-- Dependency Test Suite -->
</testng-results>
